/* Simulated Claude db/user contract: multiple users, private saves, per-character roster writes. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(root+'/sablewood-tracker.html','utf8'),meta=html.slice(html.indexOf('const CDOM='),html.indexOf('const CV=')),code='const EQ_CATALOG='+fs.readFileSync(root+'/players/equipment.json','utf8')+';\n'+fs.readFileSync(root+'/players/equipment.js','utf8')+'\n'+'const PL_CARD_RULES='+fs.readFileSync(root+'/players/card-controls.json','utf8')+';\n'+fs.readFileSync(root+'/players/card-resources.js','utf8')+'\n'+fs.readFileSync(root+'/players/card-effects.js','utf8')+'\n'+fs.readFileSync(root+'/players/class-features.js','utf8')+'\n'+fs.readFileSync(root+'/players/print-sheet.js','utf8')+'\n'+fs.readFileSync(root+'/players/player.js','utf8'),rules=JSON.parse(fs.readFileSync(root+'/players/rules.json','utf8'));
const store=new Map(),watch=new Map(),cols=new Map(),noop=()=>{};
const snap=p=>({exists:store.has(p),data:()=>store.get(p)});
const colSnap=p=>({forEach:f=>{for(const key of store.keys())if(key.startsWith(p+'/')&&!key.slice(p.length+1).includes('/'))f(snap(key))}});
function dbFor(account,gm){return {doc(p){assert.equal(p.split('/').length%2,0,'document path must have an even number of segments');if(p.startsWith('data/users/'))assert(p.startsWith('data/users/'+account+'/'),'private path must belong to user');return {get:async()=>snap(p),set:async value=>{if(p==='tavolo/campagne'||p.startsWith('tavolo/players/status/'))assert(gm,'only GM publishes directory/status');if(p.startsWith('tavolo/players/roster/'))assert.equal(JSON.parse(value.json).owner,account,'each player writes own roster document');store.set(p,JSON.parse(JSON.stringify(value)));for(const f of watch.get(p)||[])f(snap(p));const parent=p.slice(0,p.lastIndexOf('/'));for(const f of cols.get(parent)||[])f(colSnap(parent));},onSnapshot(f){watch.set(p,[...(watch.get(p)||[]),f]);f(snap(p));return noop}}},collection(p){assert.equal(p.split('/').length%2,1,'collection path must have an odd number of segments');return {doc:n=>this.doc(p+'/'+n),get:async()=>colSnap(p),onSnapshot:f=>{cols.set(p,[...(cols.get(p)||[]),f]);f(colSnap(p));return noop}}}}}
function context(account,gm){const local=new Map(),db=dbFor(account,gm);const x=vm.createContext({window:{claude:{}},document:{activeElement:null,addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[]},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},addEventListener:noop,Date,Math,JSON,Set,Map,Promise,Number,String,Object,Array,crypto:require('node:crypto').webcrypto,VIEW:{canGM:gm,tdb:db,mode:gm?'gm':'player'},APP:{view:'home',camp:null},CAMPS:{list:[{id:'campaign-1',name:'Test campaign',module:'sablewood',updated:0}]},S:{pcs:[]},PLAYER_RULES:rules,esc:s=>String(s??''),sgn:n=>(n>=0?'+':'')+n,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),cimg:()=>'',render:noop,toast:noop,scrollY:0,scrollTo:noop,setTimeout,clearTimeout,dbQueue:async(doc,v)=>{try{await doc.set(v);return true}catch(e){return false}},dbWrite:(p,v)=>db.doc(p).set(v),persist:noop,userCol:null,plTestDB:db,plTestUser:{id:async()=>account}});vm.runInContext(meta,x);vm.runInContext(code,x);return x}
const run=(c,s)=>vm.runInContext(s,c);
async function flush(){for(let i=0;i<30;i++)await Promise.resolve()}
(async()=>{
 const gm=context('gm',true),alice=context('alice',false),bob=context('bob',false);
 for(const c of [gm,alice,bob])await run(c,'playerConnect(plTestDB,plTestUser)');await flush();
 assert.equal(run(alice,'PL.directory.length'),1);assert.equal(run(bob,'PL.directory[0].name'),'Test campaign');
 for(const [c,name]of [[alice,'Alice character'],[bob,'Bob character']])run(c,`const pc=plNew();Object.assign(pc,{name:${JSON.stringify(name)},className:'Warlock',subclass:'Pact of the Endless',subcards:[282],ancestry:CARDS.find(x=>x.n==='Human').i,community:CARDS.find(x=>x.n==='Loreborne').i,background:'PRIVATE BACKGROUND',notes:'PRIVATE NOTES',classChoices:{patron:'Test',sphere:'Dreams'},campaigns:['campaign-1']});PL.chars=[pc];PL.id=pc.id;plSave(pc);plWatchGM(pc);`);
 await flush();assert.equal(run(gm,'PL.roster.length'),2,'concurrent roster joins use separate documents');assert.equal(run(alice,'PL.chars.length'),1);assert.equal(run(bob,'PL.chars.length'),1);assert.equal(run(alice,'PL.chars[0].name'),'Alice character');assert.equal(run(bob,'PL.chars[0].name'),'Bob character');
 assert(store.has('data/users/alice/personaggi'));assert(store.has('data/users/bob/personaggi'));for(const [p,v]of store)if(p.startsWith('tavolo/players/roster/')){const c=JSON.parse(v.json).character;assert.equal(c.notes,undefined);assert.equal(c.background,undefined);assert.equal(c.campaigns,undefined)}
 run(gm,`APP.camp='campaign-1';const row=PL.roster.find(x=>x.owner==='alice');S.pcs=[{id:row.character.id,playerOwner:row.owner,hp:0,st:0,hope:2,ar:0,cond:[],over:{}}];plReceiveRoster();S.pcs[0].hp=2;playerGMChanges();`);await flush();assert.equal(run(alice,'PL.chars[0].hp'),2,'GM corrections reach the owning player');assert.equal(run(bob,'PL.chars[0].hp'),0,'GM corrections do not affect another player');
 run(alice,'PL.chars[0].hp=3;plSave(PL.chars[0])');await flush();assert.equal(run(gm,'S.pcs[0].hp'),3,'player edits reach GM roster');
 await run(alice,"plLeave(PL.chars[0],'campaign-1')");await flush();assert.equal(run(gm,'PL.roster.length'),1);assert.equal(run(gm,'PL.roster[0].owner'),'bob');
 console.log('✓ Multi-user private saves, concurrent joins, public projection, GM/player track sync and campaign leave passed');
})().catch(e=>{console.error(e);process.exitCode=1});
